### ISSUE TITLE
Include an estimated time remaining in the console output?

### ISSUE THREAD

**Issue by maxheyn** [rubennp91/mcloady#1]
Loving this but I was wondering how long it would take to finish running this script when I was (still am!) using it.
Should be easy to calculate the remaining time using the time values given from the .ini file.

I had to do the math myself and ended up with about 31 hours total but it'd be nice to see the progress remaining and maybe a % complete!

Just a suggestion 😊

**Comment by rubennp91** [comment]
Hi, thanks for the suggestion, I added it with the last commit:
https://github.com/rubennp91/mcloady/commit/ca4380ea89da5a5728895faebfc85179fd8d5953
