### ISSUE TITLE
Set game rules during world generation

### ISSUE THREAD

**Issue by greenstack** [rubennp91/mcloady#5]
In [Xisuma's video](https://youtu.be/eA35S2GW-jI?t=79) (timestamp), he mentions that there are some game rules that should be set to particular values. I looked through the code, and it doesn't seem like that's happening. I think it would be useful to set these rules when generation begins or resumes. These could be toggled on or off with command-line arguments, possibly.

The game rules Xisuma mentions in particular include:

- Turning off the daylight cycle `gamerule doDaylightCycle false`
- Turning off weather `gamerule doWeatherCycle false`
- Turning off mob spawning `gamerule doMobSpawning false`

I would also recommend turning off fire ticking (`gamerule doFireTick false`).

When generation completes, the gamerules should be reset to their default values (true in each case).

This will help reduce the overhead of a user trying to do this/following along.

**Comment by rubennp91** [comment]
Added in [986c1f0](https://github.com/rubennp91/mcloady/commit/986c1f0cfa9cdd0749c9803b5dcd6b3482e0a706)
